### ISSUE TITLE
isOK failing for pages of empty lists

### ISSUE THREAD

**Issue by GertSallaerts** [JorgenEvens/rest-store#26]
Not sure if this is expected behaviour or not. Calling `isOK` always returns `false` for pages retrieved from empty lists.

When you use the `page` function to get the first page from an empty list (`state == OK && total = 0`) a simple empty array will always be returned (see below) because you are requesting a page that does not exist.

https://github.com/JorgenEvens/rest-store/blob/7461981b3b70eec9412b58915d30e6316bfe6e17/src/list/page.js#L13-L14

Such an empty array does not pass the `isOK` check because it does not have the `ENTRY` symbol attached.

Should it work like `range` maybe? (see below)

https://github.com/JorgenEvens/rest-store/blob/7461981b3b70eec9412b58915d30e6316bfe6e17/src/list/range.js#L11-L17

**Comment by JorgenEvens** [comment]
Could you create a reproduction, test-case or similar to explain your specific issue here? The first page is supposed to be `0` which is never larger than `pages = 0`. Any other page (`> 0`) should not be considered OK, so there `isOK` is working as expected.

**Comment by GertSallaerts** [comment]
This first page is `1` because pages are not zero-based. If you still need a reproduction, let me know.

https://github.com/JorgenEvens/rest-store/blob/7461981b3b70eec9412b58915d30e6316bfe6e17/src/list/_page.js#L4-L10
